package game_engine.util;

import java.util.*;
import java.util.function.Predicate;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

/**
 * Class that converts a <code>java.util.List</code> into a series of <code>Pair</code>s.
 * This is useful when you want to deal with related items in a list as pairs of objects.
 * <br><br>
 * You can convert a list into pairs by passing the list into the ListItemPairer constructor. To get the pairs, you can
 * iterate over the same instance of ListItemPairer.
 *
 * @param <T> the type of the list and the pairs generated from the list.
 */
public class ListItemPairer<T> implements Iterable<Pair<T>> {

    /**
     * the list of pairs generated by this instance.
     */
    private final List<Pair<T>> pairList = new ArrayList<>();

    /**
     * Creates the necessary pairs from <code>sourceList</code>.
     * You can then get the pairs by iterating over the <code>ListItemPairer</code> instance.
     * <br><br>
     * By default, the constructor creates the pairs in this form: <code>(null, item1), (item1, item2), (item2, item3)</code>
     * and so on, until <code>(item(n-1), item(n)), (item(n), null)</code>. The pairs with <code>null</code> values are
     * referred to as <i>null pairs</i>. The null pairs are created as it is assumed that the business need for pairing
     * might also require pairs for entering the list and exiting the list.
     * <br><br>
     * If you do not want the pairs to be for all items of the list, then you must pass in <code>java.util.function.Predicate</code>s
     * for the <code>startPositionIdentifier</code> & <code>endPositionIdentifier</code> arguments. These predicates must
     * be conditions that can point to the elements from which pairing should start and end. Passing these predicates
     * will not create the null pairs, but will start &amp; end the pairs at the specified items.
     * <br><br>
     * Note that if you pass only one of the <code>Predicate</code>s, then null pairs will be created for the other end.
     *
     * @param sourceList              the list of items out of which pairs must be created
     * @param startPositionIdentifier the condition to identify the position in the list from which pairs must be created
     * @param endPositionIdentifier   the condition to identify the position in the list at which pair creation must be
     *                                stopped
     */
    public ListItemPairer(List<T> sourceList,
          Optional<Predicate<T>> startPositionIdentifier, Optional<Predicate<T>> endPositionIdentifier) {
        if (sourceList.isEmpty()) return;

        int sourceListSize = sourceList.size() - 1;
        int startPositionIndex = 0, endPositionIndex = sourceListSize;
        if (startPositionIdentifier.isPresent()) {
            Optional<T> optionalItem = sourceList.stream().filter(startPositionIdentifier.get()).findFirst();
            startPositionIndex = sourceList.indexOf(optionalItem.get());
        }
        if (endPositionIdentifier.isPresent()) {
            List<T> reversedSourceList = IntStream.rangeClosed(0, sourceListSize)
                    .map(i -> sourceListSize - i)
                    .mapToObj(sourceList::get)
                    .collect(Collectors.toList());
            Optional<T> optionalItem = reversedSourceList.stream().filter(endPositionIdentifier.get()).findFirst();
            endPositionIndex = sourceList.indexOf(optionalItem.get());
        }

        if (startPositionIndex == 0) {
            pairList.add(new Pair<>(null, sourceList.get(0)));
        }
        for (int i = startPositionIndex; i < endPositionIndex; i++) {
            pairList.add(new Pair<>(sourceList.get(i), sourceList.get(i + 1)));
        }
        if (endPositionIndex == sourceListSize) {
            pairList.add(new Pair<>(sourceList.get(sourceListSize), null));
        }
    }

    /**
     * Returns an <code>Iterator</code> that can be used in for-each loops to get the pairs generated from the list.
     *
     * @return an iterator for getting generated pairs
     */
    public Iterator<Pair<T>> iterator() {
        return pairList.iterator();
    }
}
